### ISSUE TITLE
design: 자잘한 css 수정

### ISSUE THREAD

**Issue by dar-jeeling** [dar-jeeling/dar-jeeling.github.io#11]
# 목적

# 구현하고자 하는 것

현재 색상에 맞게 기본 템플릿 테마 색상 수정

# TODO LIST
- [ ] 모바일 사용 시, 위 쪽 색상 변경
- [ ] 코드 블럭 색상 변경
- [ ] 다크모드 시 링크 색상 변경
